#!/bin/sh

#
# Create imx8q_evk U-Boot image according to instructions in "i.MX Linux User's Guide"
# (https://www.nxp.com/webapp/Download?colCode=imx-yocto-L4.14.98_2.0.0_ga)
#
# Maximum boot image size increased from 8M to 64M
#

git clone -b imx_v2019.04_4.19.35_1.1.0 https://source.codeaurora.org/external/imx/uboot-imx
cd uboot-imx
sed -i common/bootm.c -e 's/CONFIG_SYS_BOOTM_LEN\t0x800000/CONFIG_SYS_BOOTM_LEN\t0xa000000/'
sed -i common/bootm.c -e 's\usb_stop()\//usb_stop()\'
make ARCH=arm CROSS_COMPILE=genode-aarch64- imx8mq_evk_defconfig
make ARCH=arm CROSS_COMPILE=genode-aarch64-
cd ..

git clone -b imx_4.14.98_2.0.0_ga https://source.codeaurora.org/external/imx/imx-atf
cd imx-atf
make CROSS_COMPILE=genode-aarch64- PLAT=imx8mq bl31
cd ..

wget https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/firmware-imx-8.1.bin
sh ./firmware-imx-8.1.bin --auto-accept

git clone -b imx_4.14.98_2.0.0_ga https://source.codeaurora.org/external/imx/imx-mkimage
cd imx-mkimage/iMX8M
ln -s ../../uboot-imx/tools/mkimage mkimage_uboot
ln -s ../../uboot-imx/spl/u-boot-spl.bin
ln -s ../../uboot-imx/u-boot-nodtb.bin
ln -s ../../uboot-imx/arch/arm/dts/fsl-imx8mq-evk.dtb
ln -s ../../imx-atf/build/imx8mq/release/bl31.bin
ln -s ../../firmware-imx-8.1/firmware/hdmi/cadence/signed_hdmi_imx8m.bin
ln -s ../../firmware-imx-8.1/firmware/ddr/synopsys/lpddr4_pmu_train_1d_dmem.bin
ln -s ../../firmware-imx-8.1/firmware/ddr/synopsys/lpddr4_pmu_train_1d_imem.bin
ln -s ../../firmware-imx-8.1/firmware/ddr/synopsys/lpddr4_pmu_train_2d_dmem.bin
ln -s ../../firmware-imx-8.1/firmware/ddr/synopsys/lpddr4_pmu_train_2d_imem.bin

cd ..
make SOC=iMX8M flash_evk

#############################
# manual installation steps #
#############################

#
# write image to micro SD card
#

# $ sudo dd if=imx-mkimage/iMX8M/flash.bin of=/dev/sd<?> bs=1k seek=33 conv=fsync

#
# boot via TFTP
#

# u-boot=> setenv bootcmd 'dhcp; source'
# u-boot=> saveenv

